-- --------------------------------------------------------
-- 호스트:                          10.41.2.94
-- 서버 버전:                        10.11.8-MariaDB - mariadb.org binary distribution
-- 서버 OS:                        Win64
-- HeidiSQL 버전:                  12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


DROP TABLE MYCLASS_LOG CASCADE;
DROP TABLE MYCLASS CASCADE;
DROP TABLE CLASS_LIST CASCADE;
DROP TABLE MILK_MEMBER CASCADE;
DROP TABLE REPLY CASCADE;
DROP TABLE BOARD CASCADE;
DROP TABLE TSPOON_MEMBER CASCADE;
SHOW TABLES;

-- tspoon 데이터베이스 구조 내보내기
CREATE DATABASE IF NOT EXISTS `tspoon` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `tspoon`;

-- 테이블 tspoon.tspoon_member 구조 내보내기
CREATE TABLE IF NOT EXISTS `tspoon_member` (
  `TSPOON_NO` int(11) NOT NULL AUTO_INCREMENT,
  `ID` varchar(10) NOT NULL,
  `PASSWORD` varchar(14) NOT NULL,
  `NAME` varchar(15) NOT NULL,
  `PHONE_NUM` varchar(14) NOT NULL,
  `ADDRESS` varchar(100) NOT NULL,
  `JOIN_DATE` date NOT NULL,
  `ROLE` tinyint(4) DEFAULT NULL,
  `SEX` tinyint(4) DEFAULT NULL,
  `MEMBER_YN` tinyint NOT NULL,
  PRIMARY KEY (`TSPOON_NO`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 테이블 tspoon.board 구조 내보내기
CREATE TABLE IF NOT EXISTS `board` (
  `BOARD_NO` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `ARTICLE` varchar(2000) NOT NULL,
  `BOARD_DATE` date NOT NULL,
  `BOARD_YN` tinyint(4) NOT NULL,
  `TSPOON_NO` int(11) NOT NULL,
  PRIMARY KEY (`BOARD_NO`),
  KEY `BOARD_FK` (`TSPOON_NO`),
  CONSTRAINT `BOARD_FK` FOREIGN KEY (`TSPOON_NO`) REFERENCES `tspoon_member` (`TSPOON_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 테이블 tspoon.reply 구조 내보내기
CREATE TABLE IF NOT EXISTS `reply` (
  `REPLY_NO` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` varchar(600) NOT NULL,
  `REPLY_DATE` date NOT NULL,
  `REPLY_YN` tinyint(4) NOT NULL,
  `BOARD_NO` int(11) NOT NULL,
  `TSPOON_NO` int(11) NOT NULL,
  PRIMARY KEY (`REPLY_NO`),
  KEY `REPLY_FK_BOARD` (`BOARD_NO`),
  KEY `REPLY_FK_TSPOONS` (`TSPOON_NO`),
  CONSTRAINT `REPLY_FK_BOARD` FOREIGN KEY (`BOARD_NO`) REFERENCES `board` (`BOARD_NO`),
  CONSTRAINT `REPLY_FK_TSPOONS` FOREIGN KEY (`TSPOON_NO`) REFERENCES `tspoon_member` (`TSPOON_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 테이블 tspoon.milk_member 구조 내보내기
CREATE TABLE IF NOT EXISTS `milk_member` (
  `MILKTID` varchar(8) NOT NULL,
  `NAME` varchar(15) NOT NULL,
  `birthday` date DEFAULT NULL,
  `SCHOOL` varchar(15) NOT NULL,
  `TSPOON_NO` int(11) DEFAULT NULL,
  PRIMARY KEY (`MILKTID`),
  KEY `MILK_MEMBER_FK` (`TSPOON_NO`),
  CONSTRAINT `MILK_MEMBER_FK` FOREIGN KEY (`TSPOON_NO`) REFERENCES `tspoon_member` (`TSPOON_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 테이블 tspoon.class_list 구조 내보내기
CREATE TABLE IF NOT EXISTS `class_list` (
  `CLASS_NO` int(11) NOT NULL AUTO_INCREMENT,
  `CLASS_NAME` varchar(300) NOT NULL,
  `GRADE` varchar(15) NOT NULL,
  `TEACHER` varchar(12) NOT NULL,
  `CLASS_COUNT` int(11) NOT NULL,
  `SUBJECT` varchar(10) NOT NULL,
  PRIMARY KEY (`CLASS_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 테이블 tspoon.myclass 구조 내보내기
CREATE TABLE IF NOT EXISTS `myclass` (
  `MYCLASS_NO` int(11) NOT NULL AUTO_INCREMENT,
  `MYCLASS_START_DATE` date NOT NULL,
  `MYCLASS_END_DATE` date NOT NULL,
  `COMPLETE` tinyint(4) DEFAULT NULL,
  `MYCLASS_YN` tinyint(4) NOT NULL,
  `CLASS_NO` int(11) DEFAULT NULL,
  `MILKTID` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`MYCLASS_NO`),
  KEY `MYCLASS_FK_CLASS_LIST` (`CLASS_NO`),
  KEY `MYCLASS_FK_MILK_MEMBER` (`MILKTID`),
  CONSTRAINT `MYCLASS_FK_CLASS_LIST` FOREIGN KEY (`CLASS_NO`) REFERENCES `class_list` (`CLASS_NO`),
  CONSTRAINT `MYCLASS_FK_MILK_MEMBER` FOREIGN KEY (`MILKTID`) REFERENCES `milk_member` (`MILKTID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 테이블 tspoon.myclass_log 구조 내보내기
CREATE TABLE IF NOT EXISTS `myclass_log` (
  `LOG_NO` int(11) NOT NULL AUTO_INCREMENT,
  `PROGRESS` int(11) NOT NULL,
  `LOG_DATE` date NOT NULL,
  `MYCLASS_NO` int(11) DEFAULT NULL,
  PRIMARY KEY (`LOG_NO`),
  KEY `MYCLASS_LOG_FK` (`MYCLASS_NO`),
  CONSTRAINT `MYCLASS_LOG_FK` FOREIGN KEY (`MYCLASS_NO`) REFERENCES `myclass` (`MYCLASS_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SHOW TABLES;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
